# Generated by Django 4.2.1 on 2023-05-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_profile_company_company_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='manager',
        ),
        migrations.AddField(
            model_name='company',
            name='person',
            field=models.ManyToManyField(to='main.profile', verbose_name='کاربران'),
        ),
    ]
