# Generated by Django 4.2.1 on 2023-05-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_company_manager_company_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='درباره ما'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='web_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کاربری شرکت'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='درامد ماهیانه'),
        ),
    ]
