# Generated by Django 4.2.1 on 2023-05-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ManyToManyField(to='main.company', verbose_name='شرکت وابسته'),
        ),
    ]
