# Generated by Django 4.2.1 on 2023-06-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, verbose_name='نام محصول')),
                ('type', models.CharField(choices=[('countable', 'عددی'), ('Noncountable', 'مقداری')], default='عددی', max_length=20, verbose_name='نوع محصول')),
                ('count', models.IntegerField(blank=True, default=0, verbose_name='مقدار/تعداد')),
                ('price', models.IntegerField(blank=True, default=None, verbose_name='قیمت')),
                ('company', models.ManyToManyField(blank=True, to='main.company', verbose_name='شرکت وابسته')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارشات',
            },
        ),
    ]
