# Generated by Django 4.2.1 on 2023-06-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='caption',
            field=models.TextField(blank=True, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان'),
        ),
    ]
