# Generated by Django 4.2.1 on 2023-06-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_slider_caption_alter_slider_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='نام')),
                ('caption', models.TextField(blank=True, verbose_name='متن')),
                ('photo', models.ImageField(upload_to='about/%Y/%m/%d/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
    ]
