# Generated by Django 4.2.1 on 2023-06-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='link',
            field=models.CharField(blank=True, max_length=150, verbose_name='لینک'),
        ),
    ]
