# Generated by Django 4.2.1 on 2023-06-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان')),
                ('body', models.TextField(blank=True, verbose_name='متن')),
                ('photo', models.ImageField(upload_to='news/%Y/%m/%d/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ ها',
            },
        ),
    ]
